// firebaseOptions.dart Content
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2tDdP1lEr8jlN9LBWL3lRuGKOBowCf1I',
    appId: '1:921031692290:web:9fa4bb694bb15133c1171b',
    messagingSenderId: '921031692290',
    projectId: 'intelliassist-780a0',
    authDomain: 'intelliassist-780a0.firebaseapp.com',
    storageBucket: 'intelliassist-780a0.appspot.com',
    measurementId: 'G-62XLS8PCBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1GOkIsdsZwSJAdPR5ig1eqcUz40_kQY',
    appId: '1:921031692290:android:c19f85ba991cacacc1171b',
    messagingSenderId: '921031692290',
    projectId: 'intelliassist-780a0',
    storageBucket: 'intelliassist-780a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbO8YHuDVlAhGLJut7nfL8pUYJ7UuCQPU',
    appId: '1:921031692290:ios:905e3c26d850d3abc1171b',
    messagingSenderId: '921031692290',
    projectId: 'intelliassist-780a0',
    storageBucket: 'intelliassist-780a0.appspot.com',
    iosBundleId: 'com.example.intelliassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbO8YHuDVlAhGLJut7nfL8pUYJ7UuCQPU',
    appId: '1:921031692290:ios:46963d61828b2d5cc1171b',
    messagingSenderId: '921031692290',
    projectId: 'intelliassist-780a0',
    storageBucket: 'intelliassist-780a0.appspot.com',
    iosBundleId: 'com.example.intelliassist.RunnerTests',
  );
}